### ISSUE TITLE
React native Android SDK dependancies is required updation to native android sdk latest release i.e. nss-v1.5.1

### ISSUE THREAD

**Issue by AnkitaKP** [SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#22]
Hello,

Currently android sdk dependancies in  
gigya-react-native-plugin-for-sap-customer-data-cloud  is pointed to android core sdk version 5.1.7, please refer below screenshot
<img width="590" alt="Screenshot 2022-06-13 at 5 29 43 PM" src="https://user-images.githubusercontent.com/107407851/173348904-5aab40ae-8201-4367-8d94-8b3bf7980d2e.png">
 
But  Android SDK is having latest release which is pointing to nss-v1.5.1, which has some security fixes. 

Security fix in the sdk-core/src/main/java/com/gigya/android/sdk/api/GigyaApiRequestFactory.java, where import java.util.Random is updated to import java.util.Random is required. 

Please help us to merge this tag i.e. nss-v1.5.1 to core-v5.1.7 so that it will get added in gigya-react-native-plugin sdk

**Comment by tal-mi** [comment]
Done.
