### ISSUE TITLE
socialLogin Promise not being rejected or resolved when canceling the flow on Android

### ISSUE THREAD

**Issue by DiegoSaa** [SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#40]
Hi folks,

I noticed that the `socialLogin` promise is not being resolved or rejected when canceling the normal socialLogin flow for Google, Facebook, and Apple (or when pressing outside the Google Modal) only on **Android**. I was able to reproduce it also with the example of this plugin, by adding a try, catch, and finally structure to the socialLogin and several console.log. we have a loading that keeps running forever because of this issue. Thanks!

**Comment by sagishm** [comment]
PR merged, will release soon.
