### ISSUE TITLE
Unable to build - Error no build artifacts found 

### ISSUE THREAD

**Issue by divyegd** [SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#53]
⚠️ ERROR: No build artifacts found
Expected artifacts in: $HOME/.m2/repository/gigya-android-sdk/gigya-android-sdk-core/unspecified

https://jitpack.io/com/github/SAP/gigya-android-sdk/core-v6.1.1/build.log

**Comment by tal-mi** [comment]
Issue resolved.
