### ISSUE TITLE
java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap

### ISSUE THREAD

**Issue by andrejpavlovic** [SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#6]
I'm trying to make the following call on android:

```typescript
await Gigya.send('accounts.notifySocialLogin', {});
```

But I'm seeing the entire app crash due to this error: `java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap`.

ios is working fine.

From what I can tell, the following function should be expecting a string, not a parameter map:
https://github.com/SAP/gigya-react-native-plugin-for-sap-customer-data-cloud/blob/329c26c063b4c69342e522904e8326b814a9d7cd/android/src/main/java/com/sap/gigya_rn_plugin/GigyaSdkWrapper.java#L73-L79

My guess is something more along the lines of:
```java
    void send(String api, String jsonParameters, Promise promise) {
        GigyaSdkRNLogger.log("send: called");
        promiseWrapper.promise = promise;
        gigyaInstance.send(api, mapParams(jsonParameters), new GigyaCallback<GigyaApiResponse>() {
```

**Comment by tal-mi** [comment]
Approved pull request.
Will be added in the next upcoming version.
