### ISSUE TITLE
android - version 0.3.3 broken

### ISSUE THREAD

**Issue by andrejpavlovic** [SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#71]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#react-native-plug-in-for-sap-customer-data-cloud) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-react-native-plugin-for-sap-customer-data-cloud/blob/main/CODE_OF_CONDUCT.md).

### Description

Failed to compile due to syntax issue:
https://github.com/SAP/gigya-react-native-plugin-for-sap-customer-data-cloud/blob/46e2ab178e6347c69c154edae695d4bc537fd50b/android/src/main/java/com/sap/gigya_rn_plugin/GigyaSdkWrapper.java#L58

### Reproduction

See above.

### SDK version

0.3.3

**Comment by tal-mi** [comment]
Fixed in v0.3.4
