### ISSUE TITLE
android - getConflictingAccount() throws error

### ISSUE THREAD

**Issue by andrejpavlovic** [SAP/gigya-react-native-plugin-for-sap-customer-data-cloud#9]
It seems that android handles `getConflictingAccount()` differently from ios. Doing something like this throws `Attempt to invoke virtual method 'int java.lang.String.hasCode()' on a null object reference`

```typescript
try {
  await Gigya.socialLogin(...)
} catch (e) {
  if (!(e instanceof GigyaError)) throw e;

  switch(e.getInterruption()) {
    case GigyaInterruption.conflictingAccounts: {
      const resolver = Gigya.resolverFactory.getResolver(e) as LinkAccountResolver;
      const conflicting = await resolver.getConflictingAccount(); // <-- throws native error on android
    }
  }
```

Seems like react native plugin on android needs to call `requestConflictingAccounts` before `getConflictingAccounts`.

**Comment by andrejpavlovic** [comment]
Oh sorry, the code I'm actually running is a bit different. I'm not using `Gigya.socialLogin`, but rather just notify.

```typescript
try {
  await Gigya.send('accounts.notifySocialLogin', {
    providerSessions: ...
  })
} catch (e) {
  if (!(e instanceof GigyaError)) throw e;

  switch(e.getInterruption()) {
    case GigyaInterruption.conflictingAccounts: {
      const resolver = Gigya.resolverFactory.getResolver(e) as LinkAccountResolver;
      const conflicting = await resolver.getConflictingAccount(); // <-- throws native error on android
    }
  }

**Comment by andrejpavlovic** [comment]
I guess I would need to implement a `notifySocialLogin` helper that handles errors in the same way as `socialLogin` in order to get this to work.

https://github.com/SAP/gigya-react-native-plugin-for-sap-customer-data-cloud/blob/76a4517170513e0907809085ea96a0b98b810342/android/src/main/java/com/sap/gigya_rn_plugin/GigyaSdkWrapper.java#L225-L261

**Comment by tal-mi** [comment]
Yes, you will need to implement it as the default send request does not handle these interruptions.
